version: '3.7'

services:
  api:
    build:
      context: ./bookstore_api
      dockerfile: Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./bookstore_api:/app
    ports:
      - 8000:8000
    env_file:
      - .env

  db:
    image: postgres:13.11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=helm_bookstore_api
      - POSTGRES_USER=helm_admin
      - POSTGRES_PASSWORD=password
